#!/usr/bin/env bash

# Set environment variables for dev or CI
export APP_PORT=${APP_PORT:-80}
export DB_PORT=${DB_PORT:-3306}
export DB_ROOT_PASS=${DB_ROOT_PASS:-secret}
export DB_NAME=${DB_NAME:-helpspot}
export DB_USER=${DB_USER:-helpspot}
export DB_PASS=${DB_PASS:-secret}

COMPOSE="docker-compose"

if [ $# -gt 0 ];then
  if [ "$1" == "art" ]; then
    shift 1
    $COMPOSE run --rm \
      -w /var/www/html \
      app \
      php artisan "$@"
  # If "composer" is used, pass-thru to "composer"
  # inside a new container
  elif [ "$1" == "composer" ]; then
    shift 1
    $COMPOSE run --rm \
      -w /var/www/html \
      app \
      composer "$@"
  # If "test" is used, run unit tests,
  #pass-thru any extra arguments to php-unit
  elif [ "$1" == "test" ]; then
    shift 1
    $COMPOSE run --rm \
      -w /var/www/html \
      app \
      ./vendor/bin/phpunit "$@"
  # If "npm" is used, run npm
  # from our node container
  elif [ "$1" == "npm" ]; then
    shift 1
    $COMPOSE run --rm \
      -w /var/www/html \
      node \
      npm "$@"
  else
    $COMPOSE "$@"
  fi
else
  $COMPOSE ps
fi
